// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69vZjp_EdeTozCosYFz1-Z4mP0AztVfA',
    appId: '1:475358697507:web:843555b8fefd24034ab996',
    messagingSenderId: '475358697507',
    projectId: 'lifecuts-clone-test',
    authDomain: 'lifecuts-clone-test.firebaseapp.com',
    storageBucket: 'lifecuts-clone-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEPQqf1w-I0I4DeEkbifw4Ypszu5Gfpbk',
    appId: '1:475358697507:android:5b83d717a24327544ab996',
    messagingSenderId: '475358697507',
    projectId: 'lifecuts-clone-test',
    storageBucket: 'lifecuts-clone-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkE1tnydbrKEhygs7k-p5HKXfIMkFyeeg',
    appId: '1:475358697507:ios:c66b2cec77dcbda64ab996',
    messagingSenderId: '475358697507',
    projectId: 'lifecuts-clone-test',
    storageBucket: 'lifecuts-clone-test.appspot.com',
    iosClientId:
        '475358697507-t9177s9ems6qc9c9c0ra9i8vtbpm92ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifefourcutsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkE1tnydbrKEhygs7k-p5HKXfIMkFyeeg',
    appId: '1:475358697507:ios:c66b2cec77dcbda64ab996',
    messagingSenderId: '475358697507',
    projectId: 'lifecuts-clone-test',
    storageBucket: 'lifecuts-clone-test.appspot.com',
    iosClientId:
        '475358697507-t9177s9ems6qc9c9c0ra9i8vtbpm92ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifefourcutsClone',
  );
}
